begin;

create table if not exists public.public_contact_rate_limits (
  id bigint generated by default as identity primary key,
  rate_key text not null,
  bucket_start timestamptz not null,
  attempts integer not null default 1 check (attempts >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (rate_key, bucket_start)
);

create index if not exists public_contact_rate_limits_bucket_idx
on public.public_contact_rate_limits (bucket_start desc);

create or replace function public.bump_public_contact_rate_limit(
  p_rate_key text,
  p_bucket_start timestamptz
)
returns integer
language sql
security definer
set search_path = public
as $$
  insert into public.public_contact_rate_limits as t (rate_key, bucket_start, attempts)
  values (p_rate_key, p_bucket_start, 1)
  on conflict (rate_key, bucket_start)
  do update
    set attempts = t.attempts + 1,
        updated_at = now()
  returning attempts;
$$;

revoke all on table public.public_contact_rate_limits from anon, authenticated;
revoke all on function public.bump_public_contact_rate_limit(text, timestamptz) from public, anon, authenticated;

commit;
