create table if not exists public.referral_email_invites (
  id bigint generated by default as identity primary key,
  inviter_user_id uuid not null references public.profiles(id) on delete cascade,
  invitee_email text not null,
  code_used text not null,
  claimed_by_user_id uuid references public.profiles(id) on delete set null,
  claimed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint referral_email_invites_email_not_blank check (length(trim(invitee_email)) > 0),
  constraint referral_email_invites_code_not_blank check (length(trim(code_used)) > 0)
);

create unique index if not exists referral_email_invites_invitee_email_key
  on public.referral_email_invites ((lower(trim(invitee_email))));

create unique index if not exists referral_email_invites_claimed_by_user_id_key
  on public.referral_email_invites (claimed_by_user_id)
  where claimed_by_user_id is not null;

create index if not exists referral_email_invites_inviter_user_id_idx
  on public.referral_email_invites (inviter_user_id);

alter table public.referral_email_invites enable row level security;

drop policy if exists referral_email_invites_select_involved on public.referral_email_invites;
create policy referral_email_invites_select_involved
on public.referral_email_invites
for select
to authenticated
using (inviter_user_id = auth.uid() or claimed_by_user_id = auth.uid());

drop trigger if exists referral_email_invites_handle_updated_at on public.referral_email_invites;
create trigger referral_email_invites_handle_updated_at
before update on public.referral_email_invites
for each row
execute function public.handle_updated_at();

create or replace function public.create_referral_email_invite(p_invitee_email text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text := lower(trim(coalesce(p_invitee_email, '')));
  v_inviter public.profiles%rowtype;
  v_existing_invite public.referral_email_invites%rowtype;
  v_inviter_email text;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if v_email = '' then
    raise exception 'Invite email is required';
  end if;

  if v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception 'Invite email is invalid';
  end if;

  perform public.ensure_my_friend_code();

  select *
  into v_inviter
  from public.profiles
  where id = auth.uid()
  for update;

  if not found then
    raise exception 'Profile not found';
  end if;

  select lower(trim(coalesce(email, '')))
  into v_inviter_email
  from auth.users
  where id = auth.uid();

  if v_inviter_email <> '' and v_inviter_email = v_email then
    raise exception 'You cannot invite your own email address';
  end if;

  if exists (
    select 1
    from auth.users
    where lower(trim(coalesce(email, ''))) = v_email
  ) then
    raise exception 'This email already belongs to an existing account';
  end if;

  select *
  into v_existing_invite
  from public.referral_email_invites
  where lower(trim(invitee_email)) = v_email
  for update;

  if found then
    if v_existing_invite.claimed_by_user_id is not null then
      raise exception 'This email already completed an invitation';
    end if;

    if v_existing_invite.inviter_user_id = auth.uid() then
      raise exception 'This email has already been invited';
    end if;

    raise exception 'This email was already invited by another account';
  end if;

  insert into public.referral_email_invites (
    inviter_user_id,
    invitee_email,
    code_used
  ) values (
    auth.uid(),
    v_email,
    upper(trim(v_inviter.friend_code))
  );

  return jsonb_build_object(
    'ok', true,
    'invitee_email', v_email,
    'invite_code', upper(trim(v_inviter.friend_code))
  );
end;
$$;

revoke all on function public.create_referral_email_invite(text) from public;
grant execute on function public.create_referral_email_invite(text) to authenticated;

create or replace function public.apply_invitation_code(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text := upper(trim(coalesce(p_code, '')));
  v_inviter public.profiles%rowtype;
  v_invitee public.profiles%rowtype;
  v_pending_invite public.referral_email_invites%rowtype;
  v_invitee_created_at timestamptz;
  v_invitee_email text;
  v_referral_count integer := 0;
  v_new_reward_cycles integer := 0;
  v_cycles_to_award integer := 0;
  v_reward_months integer := 0;
  v_reward_expires_at timestamptz;
  v_base_reward_expires_at timestamptz;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if v_code = '' then
    raise exception 'Invitation code is required';
  end if;

  perform public.ensure_my_friend_code();

  select *
  into v_invitee
  from public.profiles
  where id = auth.uid()
  for update;

  if not found then
    raise exception 'Profile not found';
  end if;

  select created_at, lower(trim(coalesce(email, '')))
  into v_invitee_created_at, v_invitee_email
  from auth.users
  where id = auth.uid();

  if v_invitee_created_at is null then
    raise exception 'Account not found';
  end if;

  if coalesce(v_invitee_email, '') = '' then
    raise exception 'Your account email is required to redeem an invitation code';
  end if;

  if v_invitee_created_at < now() - interval '24 hours' then
    raise exception 'Invitation codes only work for new accounts within 24 hours of signup';
  end if;

  if v_invitee.referred_by_user_id is not null then
    raise exception 'You already used an invitation code';
  end if;

  select *
  into v_inviter
  from public.profiles
  where upper(coalesce(friend_code, '')) = v_code
  for update;

  if not found then
    raise exception 'Invitation code not found';
  end if;

  if v_inviter.id = auth.uid() then
    raise exception 'You cannot use your own invitation code';
  end if;

  select *
  into v_pending_invite
  from public.referral_email_invites
  where lower(trim(invitee_email)) = v_invitee_email
  for update;

  if not found then
    raise exception 'This account email was not invited by a friend';
  end if;

  if v_pending_invite.inviter_user_id <> v_inviter.id then
    raise exception 'This invitation code does not match the email invitation sent to this account';
  end if;

  if exists (
    select 1
    from public.referral_code_redemptions r
    where r.invitee_user_id = auth.uid()
  ) then
    raise exception 'You already used an invitation code';
  end if;

  insert into public.referral_code_redemptions (
    inviter_user_id,
    invitee_user_id,
    code_used
  ) values (
    v_inviter.id,
    auth.uid(),
    v_code
  );

  update public.referral_email_invites
  set claimed_by_user_id = auth.uid(),
      claimed_at = coalesce(claimed_at, now())
  where id = v_pending_invite.id;

  update public.profiles
  set referred_by_user_id = v_inviter.id,
      referred_by_code = v_code,
      updated_at = now()
  where id = auth.uid();

  select count(*)
  into v_referral_count
  from public.referral_code_redemptions r
  join auth.users invitee_user
    on invitee_user.id = r.invitee_user_id
  where r.inviter_user_id = v_inviter.id
    and r.created_at <= invitee_user.created_at + interval '24 hours';

  v_new_reward_cycles := floor(v_referral_count / 3.0)::integer;
  v_cycles_to_award := greatest(v_new_reward_cycles - coalesce(v_inviter.referral_reward_cycles_awarded, 0), 0);

  if v_cycles_to_award > 0 then
    v_reward_months := v_cycles_to_award;
    v_base_reward_expires_at := case
      when v_inviter.premium_referral_expires_at is not null and v_inviter.premium_referral_expires_at > now()
        then v_inviter.premium_referral_expires_at
      else now()
    end;
    v_reward_expires_at := v_base_reward_expires_at + make_interval(months => v_reward_months);

    update public.profiles
    set premium_referral_expires_at = v_reward_expires_at,
        referral_reward_cycles_awarded = v_new_reward_cycles,
        last_referral_reward_at = now(),
        last_premium_granted_at = now(),
        last_premium_granted_source = 'referral',
        updated_at = now()
    where id = v_inviter.id;

    insert into public.p2p_requests (
      type,
      from_user_id,
      to_user_id,
      status,
      message,
      request_payload
    ) values (
      'referral_reward',
      auth.uid(),
      v_inviter.id,
      'approved',
      format(
        'Your invite code just hit %s uses. Premium is active until %s.',
        v_referral_count,
        to_char(v_reward_expires_at at time zone 'UTC', 'Mon DD, YYYY')
      ),
      jsonb_build_object(
        'reward_months', v_reward_months,
        'referral_count', v_referral_count,
        'premium_expires_at', v_reward_expires_at,
        'invite_code', v_inviter.friend_code
      )
    );
  end if;

  return jsonb_build_object(
    'ok', true,
    'inviter_user_id', v_inviter.id,
    'referral_count', v_referral_count,
    'rewarded', v_cycles_to_award > 0,
    'reward_months', v_reward_months,
    'premium_expires_at', v_reward_expires_at
  );
end;
$$;

revoke all on function public.apply_invitation_code(text) from public;
grant execute on function public.apply_invitation_code(text) to authenticated;
